COPY_LOCATION = 'COPY_LOCATION_SPACE_SWITCHING'
COPY_ROTATION = 'COPY_ROTATION_SPACE_SWITCHING'
SPACE_SWITCH_POSTFIX = '_SpaceSwitch'
TARGET_OBJECT = 'sp_target_object'
SWITCHER_OBJECT = 'sp_switcher_object'
IS_SWITCHER = 'sp_is_switcher'
ACTION_PREFIX = '[SpaceSwitcher]'

